Vagrant.configure(2) do |config|

    # OS for VM
    config.vm.box = "ubuntu/xenial64"

    # VM network configuration
    config.vm.define "db-server" do |db|
        db.vm.network "forwarded_port", guest: 3306, host: 3306
        db.vm.network "forwarded_port", guest: 80, host: 3306
        db.vm.provision "shell", path: "bootstrap.sh"
    end

    # VM performance config
     config.vm.provider :virtualbox do |vb|
        vb.customize [
        'modifyvm', :id,
        '--natdnshostresolver1', 'on',
        '--memory', '1024',
        '--cpus', '2'
    ] 
  end
end   