version: '3'

services:
  # Database
  db:
    image: mysql:latest
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    deploy:
        resources:
            limits:
              cpus: '1'
              memory: 1024M
            reservations:
              cpus: '0.5'
              memory: 512M     
    environment:
      MYSQL_ROOT_PASSWORD: M300
      MYSQL_DATABASE: wordpress
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql
    networks:
      - wpsite

  # phpmyadmin
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin:latest
    restart: always
    deploy:
        resources:
            limits:
              cpus: '1'
              memory: 1024M
            reservations:
              cpus: '0.5'
              memory: 512M           
    ports:
      - '3306:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password 
    networks:
      - wpsite

  # Wordpress
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    ports:
      - '8081:80'
    restart: always
    deploy:
        resources:
            limits:
              cpus: '1'
              memory: 1024M
            reservations:
              cpus: '0.5'
              memory: 512M       
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: mysql
      WORDPRESS_DB_PASSWORD: mysql
    volumes: ['./:/var/www/html']
    networks:
      - wpsite
networks:
  wpsite:
volumes:
  db_data: